spring:
  datasource:
    url: jdbc:mysql://localhost:3306/server
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


mybatis:
  mapper-locations: classpath:mapper/*.xml

  pagehelper:
    helper-dialect: mysql
    reasonable: true
    support-methods-arguments: true
    params: count=countSql

logging:
  level:
    com.example.myspringboot0206 : debug


